apiVersion: v1
kind: Namespace
metadata:
  name: devops-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-cache
  namespace: devops-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cache
  template:
    metadata:
      labels:
        app: cache
    spec:
      containers:
      - name: cache-container
        image: routerdi1315.uv.es:443/cache:TAG
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: deployment-service
  namespace: devops-demo
spec:
  selector:
    app: cache
  ports:
    - protocol: TCP
      port:  8080
      targetPort: 8080
      nodePort: 31800
  type: NodePort
